# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

# Common configuration for MinIO services
x-minio-common: &minio-common
  image: minio/minio:RELEASE.2025-02-28T09-55-16Z
  command: server --console-address ":9001" http://minio{1...2}/data{1...2}
  expose:
    - "9000"
    - "9001"
  env_file:
      - ${PWD}/minio/.env

services:
  minio-node1:
    <<: *minio-common
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio1-data1:/data1
      - minio1-data1:/data2

  minio-node2:
    <<: *minio-common
    volumes:
      - minio2-data1:/data1
      - minio2-data2:/data2

volumes:
  minio1-data1:
  minio1-data2:
  minio2-data1:
  minio2-data2:
